# Generated by Django 3.2.6 on 2021-08-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('house', models.IntegerField(verbose_name='house')),
                ('opening_time', models.TimeField(verbose_name='opening time')),
                ('closing_time', models.TimeField(verbose_name='closing time')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='street_id', to='city.street', verbose_name='street id')),
            ],
        ),
    ]
